/**
 * Glossario delle competenze professionali del futuro
 * Usato da CompetenzaTag per mostrare definizioni al click.
 * Fonte: elaborazione originale ProfTecnologIA, Maggio 2026.
 */

export interface CompetenzaEntry {
  categoria: string;
  emoji: string;
  definizione: string;
  esempio: string;
  area_correlata?: string;
}

export const GLOSSARIO: Record<string, CompetenzaEntry> = {
  "economia circolare": {
    categoria: "Sostenibilità",
    emoji: "♻️",
    definizione: "Saper progettare prodotti e sistemi in modo che i materiali vengano riusati, riparati o riciclati invece di finire in discarica. Chi lavora con l'economia circolare aiuta aziende e istituzioni a passare da 'usa e getta' a 'usa di nuovo'.",
    esempio: "Un ingegnere dell'economia circolare ridisegna le scarpe in modo che si smontino facilmente: gomma, tessuto e schiuma possono essere riciclati separatamente.",
    area_correlata: "MAT",
  },
  "efficienza energetica": {
    categoria: "Energia",
    emoji: "⚡",
    definizione: "Capacità di ridurre la quantità di energia necessaria per fare la stessa cosa — illuminare un ufficio, riscaldare un edificio, far funzionare una macchina.",
    esempio: "Un energy manager installa sensori di presenza per le luci e isola le pareti di una scuola: riduce i consumi del 40% senza cambiare il comfort.",
    area_correlata: "ENE",
  },
  "reportistica esg": {
    categoria: "Sostenibilità aziendale",
    emoji: "📊",
    definizione: "Saper raccogliere, elaborare e comunicare i dati ambientali, sociali e di governance (ESG) di un'azienda. Le grandi aziende europee sono obbligate per legge a pubblicare questi rapporti dal 2024.",
    esempio: "Un analista ESG calcola quanta CO₂ emette ogni prodotto dell'azienda e presenta il tutto in un rapporto che investitori e clienti leggono prima di scegliere con chi lavorare.",
    area_correlata: "SIS",
  },
  "logistica sostenibile": {
    categoria: "Trasporti e supply chain",
    emoji: "🚛",
    definizione: "Progettare e gestire il trasporto di merci riducendo emissioni, sprechi e costi: scelta dei mezzi, ottimizzazione dei percorsi, riduzione degli imballaggi.",
    esempio: "Un logista sostenibile analizza 500 spedizioni settimanali e trova che il 30% può essere consolidato in meno viaggi, riducendo km e CO₂.",
    area_correlata: "COM",
  },
  "gis": {
    categoria: "Tecnologie geospaziali",
    emoji: "🗺️",
    definizione: "GIS (Geographic Information System) è un sistema informatico che permette di visualizzare, analizzare e interpretare dati geografici su mappe interattive. Si usa per pianificare città, gestire trasporti, monitorare l'ambiente.",
    esempio: "Un urban planner sovrappone mappa del traffico, piste ciclabili e zone a rischio alluvione e decide dove costruire nuovi percorsi protetti.",
    area_correlata: "AMB",
  },
  "ethical hacking": {
    categoria: "Cybersecurity",
    emoji: "🔐",
    definizione: "Simulare attacchi informatici contro sistemi autorizzati per trovare le vulnerabilità prima che lo facciano gli hacker malintenzionati. È legale solo con il permesso scritto del proprietario.",
    esempio: "Un ethical hacker viene pagato da una banca per tentare di entrare nei suoi sistemi: trova una falla nel software e la segnala prima che qualcun altro la sfrutti.",
    area_correlata: "DIG",
  },
  "sicurezza informatica": {
    categoria: "Cybersecurity",
    emoji: "🛡️",
    definizione: "Insieme di tecniche per proteggere computer, reti e dati da accessi non autorizzati: crittografia, autenticazione, firewall, backup e formazione degli utenti.",
    esempio: "Un analista monitora il traffico di rete di un ospedale 24h su 24 e blocca in tempo reale un attacco proveniente dall'estero.",
    area_correlata: "DIG",
  },
  "analisi vulnerabilità": {
    categoria: "Cybersecurity",
    emoji: "🔍",
    definizione: "Processo sistematico per identificare i punti deboli di un sistema: software non aggiornati, password deboli, configurazioni errate — prima che vengano sfruttati.",
    esempio: "Uno scan su 500 computer aziendali rivela che 80 hanno il sistema operativo non aggiornato. La patch viene applicata subito.",
    area_correlata: "DIG",
  },
  "gdpr": {
    categoria: "Privacy e diritto digitale",
    emoji: "⚖️",
    definizione: "Il GDPR è la legge europea sulla protezione dei dati personali. Saperlo applicare significa progettare sistemi che rispettano i diritti degli utenti: accesso, cancellazione, portabilità dei propri dati.",
    esempio: "Un consulente GDPR aiuta un e-commerce a capire quali dati raccoglie, per quanto tempo li conserva, e come permettere la cancellazione facilmente.",
    area_correlata: "DIG",
  },
  "digcomp 3.0": {
    categoria: "Competenze digitali",
    emoji: "💻",
    definizione: "Framework europeo che definisce le competenze digitali di tutti i cittadini. Chi lo conosce può valutare il livello digitale di persone o organizzazioni e progettare percorsi di formazione mirati.",
    esempio: "Un formatore valuta le competenze degli insegnanti con DigComp, identifica le lacune sulla sicurezza online e organizza un corso specifico.",
    area_correlata: "DIG",
  },
  "media literacy": {
    categoria: "Competenze digitali",
    emoji: "📱",
    definizione: "Capacità di leggere criticamente i media digitali: riconoscere fonti affidabili, identificare notizie false, capire come funzionano gli algoritmi, produrre contenuti responsabili.",
    esempio: "Un esperto insegna a verificare le immagini virali con il reverse image search e a riconoscere i segnali di una notizia costruita per creare panico.",
    area_correlata: "DIG",
  },
  "cybersecurity base": {
    categoria: "Cybersecurity",
    emoji: "🔒",
    definizione: "Pratiche fondamentali di sicurezza informatica: gestione delle password, riconoscimento del phishing, aggiornamenti del software, backup dei dati, navigazione sicura.",
    esempio: "Un formatore insegna ai dipendenti di una PMI a usare un password manager e ad attivare l'autenticazione a due fattori — riducendo il rischio di attacco del 70%.",
    area_correlata: "DIG",
  },
  "formazione digitale": {
    categoria: "Educazione",
    emoji: "🎓",
    definizione: "Progettare e condurre percorsi di apprendimento sulle competenze digitali per diversi tipi di utenti: studenti, lavoratori, anziani.",
    esempio: "Un formatore crea un corso online per insegnanti che non hanno mai usato strumenti di collaborazione digitale: video brevi, esercizi pratici, assistenza individuale.",
    area_correlata: "DIG",
  },
  "prototipazione rapida": {
    categoria: "Progettazione",
    emoji: "🖨️",
    definizione: "Costruire velocemente un primo modello fisico o digitale di un oggetto per testarlo e migliorarlo prima di produrlo in serie. Si usano stampa 3D, laser cutting, CNC.",
    esempio: "Un designer stampa il prototipo di un manico ergonomico in 4 ore, lo fa testare a 10 utenti, raccoglie feedback e stampa una versione migliorata lo stesso giorno.",
    area_correlata: "DIS",
  },
  "bim modeling": {
    categoria: "Architettura e costruzioni",
    emoji: "🏗️",
    definizione: "BIM (Building Information Modeling) è progettare edifici come modelli 3D digitali intelligenti dove ogni elemento ha dimensioni, materiale, costo e vita utile. Permette di simulare il comportamento dell'edificio prima di costruirlo.",
    esempio: "Un progettista BIM crea il modello di una scuola: simula il consumo energetico, trova i conflitti tra impianti, calcola il costo di ogni variante — tutto prima del primo mattone.",
    area_correlata: "DIS",
  },
  "autocad": {
    categoria: "Software di progettazione",
    emoji: "📐",
    definizione: "Il software di disegno tecnico 2D più usato nel mondo professionale. Permette di creare piante, sezioni, prospetti e dettagli tecnici con precisione millimetrica.",
    esempio: "Un tecnico disegna la pianta di un appartamento da ristrutturare, posiziona pareti, porte e impianti, e produce tavole tecniche per l'impresa edile.",
    area_correlata: "DIS",
  },
  "revit": {
    categoria: "Software BIM",
    emoji: "🏛️",
    definizione: "Principale software BIM di Autodesk. Permette modelli 3D intelligenti dove ogni elemento è collegato agli altri: se sposti una parete, porte e finestre si aggiornano automaticamente.",
    esempio: "Un architetto progetta un ospedale in Revit: quando il cliente chiede di cambiare i pavimenti, il software calcola automaticamente il nuovo costo e aggiorna tutte le tavole.",
    area_correlata: "DIS",
  },
  "disegno tecnico avanzato": {
    categoria: "Progettazione",
    emoji: "✏️",
    definizione: "Padronanza completa del linguaggio grafico tecnico: proiezioni, sezioni, quotatura, tolleranze geometriche, norme ISO/UNI. Il linguaggio con cui ingegneri e architetti comunicano ai costruttori.",
    esempio: "Un progettista meccanico disegna un componente di motore con tutte le quote e tolleranze. Il disegno viene inviato a una fonderia in Polonia che lo produce esattamente come specificato.",
    area_correlata: "DIS",
  },
  "leed": {
    categoria: "Certificazioni ambientali",
    emoji: "🌿",
    definizione: "LEED (Leadership in Energy and Environmental Design) è la più diffusa certificazione internazionale per edifici sostenibili. Un edificio LEED dimostra di usare poca energia, poca acqua e materiali sostenibili.",
    esempio: "Un consulente LEED verifica che i materiali siano certificati, che il fotovoltaico copra il 40% dei consumi, che ci siano colonnine per bici — e ottiene la certificazione LEED Gold.",
    area_correlata: "AMB",
  },
  "materiali bio-based": {
    categoria: "Sostenibilità",
    emoji: "🌱",
    definizione: "Conoscere, valutare e progettare con materiali derivati da fonti biologiche rinnovabili — amido di mais, canna da zucchero, mycelium, fibre naturali — in sostituzione dei materiali fossili.",
    esempio: "Un designer sostituisce la schiuma di polistirolo negli imballaggi con mycelium (radici di funghi): stesso potere ammortizzante, completamente biodegradabile in 30 giorni.",
    area_correlata: "MAT",
  },
  "bim": {
    categoria: "Architettura e costruzioni",
    emoji: "🏗️",
    definizione: "Metodologia in cui architetti, ingegneri e costruttori collaborano su un unico modello digitale dell'edificio. Riduce errori, costi e tempi di costruzione.",
    esempio: "In un cantiere BIM, quando l'impiantista aggiunge un tubo, il sistema avvisa automaticamente se entra in conflitto con una trave strutturale.",
    area_correlata: "AMB",
  },
  "pianificazione urbana": {
    categoria: "Urbanistica",
    emoji: "🏙️",
    definizione: "Disciplina che studia e progetta lo sviluppo delle città: dove si costruiscono case, uffici, parchi, strade, scuole. Bilancia bisogni degli abitanti, sostenibilità e fattibilità economica.",
    esempio: "Un urban planner analizza un quartiere periferico: decide dove costruire la nuova fermata del metro, quale via pedonalizzare e dove serve un parco, coinvolgendo i cittadini.",
    area_correlata: "AMB",
  },
  "mobilità sostenibile": {
    categoria: "Trasporti",
    emoji: "🚲",
    definizione: "Progettare e promuovere sistemi di trasporto che riducono emissioni e congestione: piste ciclabili, trasporto pubblico efficiente, veicoli elettrici, car sharing.",
    esempio: "Un consulente analizza gli spostamenti casa-lavoro dei dipendenti di un'azienda e propone abbonamenti al trasporto pubblico e due giorni di smart working — riduzione del 35% delle auto.",
    area_correlata: "AMB",
  },
  "nature-based solutions": {
    categoria: "Sostenibilità ambientale",
    emoji: "🌳",
    definizione: "Soluzioni ispirate dalla natura per problemi urbani: tetti verdi che isolano e assorbono l'acqua, alberi in città che riducono le temperature, paludi artificiali che depurano le acque.",
    esempio: "Tetti verdi su tutti gli edifici pubblici di un quartiere: in estate la temperatura scende di 3°C, le alluvioni si riducono del 40% e la biodiversità aumenta.",
    area_correlata: "AMB",
  },
  "sicurezza alimentare": {
    categoria: "Industria alimentare",
    emoji: "🍽️",
    definizione: "Garantire che gli alimenti prodotti siano sicuri per il consumo: assenza di patogeni e contaminanti. Include gestione della catena del freddo, controlli di laboratorio e certificazioni.",
    esempio: "Un responsabile controlla temperatura e umidità in ogni fase della produzione casearia, esegue test microbiologici e garantisce che nessun lotto esca con contaminazioni.",
    area_correlata: "ALI",
  },
  "haccp": {
    categoria: "Industria alimentare",
    emoji: "📋",
    definizione: "Sistema obbligatorio in tutti gli stabilimenti alimentari europei. Identifica i punti critici del processo produttivo dove un pericolo può contaminare il cibo e stabilisce i controlli necessari.",
    esempio: "In un pastificio, il tecnico HACCP identifica la fase di cottura come punto critico: installa sensori di temperatura e un sistema di allarme automatico.",
    area_correlata: "ALI",
  },
  "etichettatura": {
    categoria: "Industria alimentare",
    emoji: "🏷️",
    definizione: "Conoscenza della normativa europea sull'etichettatura degli alimenti: ingredienti, valori nutrizionali, allergeni, date di scadenza, indicazioni di origine.",
    esempio: "Un esperto verifica che le etichette di biscotti rispettino il Regolamento UE 1169/2011: allergeni in grassetto, valori nutrizionali per 100g e per porzione.",
    area_correlata: "ALI",
  },
  "analisi nutrizionale": {
    categoria: "Nutrizione",
    emoji: "🥗",
    definizione: "Calcolare e interpretare i valori nutrizionali di alimenti e pasti: calorie, macronutrienti, vitamine, minerali. Si usa per formulare nuovi prodotti o valutare la qualità di una dieta.",
    esempio: "Un nutrizionista industriale analizza una nuova barretta per ciclisti: calcola proteine e carboidrati, verifica le normative e ottimizza la formulazione.",
    area_correlata: "ALI",
  },
  "tracciabilità filiera": {
    categoria: "Supply chain",
    emoji: "🔗",
    definizione: "Seguire un prodotto in ogni fase della catena produttiva — dal campo al consumatore — documentando ogni passaggio per garantire qualità, sicurezza e rispetto degli standard etici.",
    esempio: "Un sistema QR code permette al consumatore di scannerizzare una tavoletta di cioccolato e vedere la fattoria in Ecuador dove è stato coltivato il cacao.",
    area_correlata: "ALI",
  },
  "logistica alimentare": {
    categoria: "Supply chain",
    emoji: "📦",
    definizione: "Gestione del trasporto e dello stoccaggio degli alimenti rispettando la catena del freddo, i tempi di consegna e le normative igieniche.",
    esempio: "Un logista organizza la distribuzione di 10.000 kg di pesce fresco ogni giorno da Genova ai ristoranti del nord Italia, garantendo i 2-4°C in tutto il percorso.",
    area_correlata: "ALI",
  },
  "certificazioni dop/igp": {
    categoria: "Qualità agroalimentare",
    emoji: "🏅",
    definizione: "DOP (Denominazione di Origine Protetta) e IGP (Indicazione Geografica Protetta) sono certificazioni europee che garantiscono che un prodotto provenga da una zona specifica e sia prodotto secondo metodi tradizionali.",
    esempio: "Un consulente accompagna un consorzio di produttori di mozzarella di bufala campana nell'iter di certificazione DOP europeo.",
    area_correlata: "ALI",
  },
  "sostenibilità": {
    categoria: "Sostenibilità",
    emoji: "🌍",
    definizione: "Valutare e ridurre l'impatto ambientale e sociale di prodotti, processi e organizzazioni. Include SDG, analisi LCA, rendicontazione ESG e strategie di riduzione delle emissioni.",
    esempio: "Un manager calcola l'impronta idrica di ogni capo di abbigliamento e stabilisce un piano per ridurre i consumi d'acqua del 50% in tre anni.",
    area_correlata: "MAT",
  },
  "analisi di processo": {
    categoria: "Business",
    emoji: "⚙️",
    definizione: "Mappare, misurare e migliorare i processi aziendali: dove si perdono tempo e risorse, dove si possono fare automazioni. Si usano diagrammi di flusso, dati e interviste.",
    esempio: "Un business analyst scopre che le fatture impiegano 45 giorni invece dei 15 necessari: identifica 3 colli di bottiglia e propone un'automazione che riduce i tempi del 60%.",
    area_correlata: "SIS",
  },
  "kpi": {
    categoria: "Business",
    emoji: "📈",
    definizione: "KPI (Key Performance Indicator) sono le misure quantitative che indicano se un'organizzazione sta raggiungendo i suoi obiettivi. Saper sceglierli, misurarli e interpretarli è essenziale per prendere decisioni basate sui dati.",
    esempio: "Un manager definisce 5 KPI per un negozio online: tasso di conversione, valore medio dell'ordine, tempo di risposta, tasso di reso, NPS. Li monitora ogni settimana.",
    area_correlata: "SIS",
  },
  "lean management": {
    categoria: "Business",
    emoji: "🏭",
    definizione: "Filosofia nata dalla Toyota che punta a eliminare tutti gli sprechi (tempo, materiali, movimenti, attese) dai processi produttivi e aziendali.",
    esempio: "Un consulente lean riorganizza una fabbrica di mobili: elimina il magazzino intermedio e riduce il tempo di produzione di un tavolo da 8 giorni a 3.",
    area_correlata: "SIS",
  },
  "digital transformation": {
    categoria: "Business e tecnologia",
    emoji: "🔄",
    definizione: "Processo con cui un'organizzazione integra le tecnologie digitali in tutti i suoi processi, cambiando il modo in cui opera. Include automazione, analisi dei dati, cloud computing.",
    esempio: "Un consulente aiuta una fabbrica a connettere le macchine a Internet (IoT) e raccogliere dati in tempo reale per prevedere i guasti prima che fermino la linea produttiva.",
    area_correlata: "SIS",
  },
  "business model canvas": {
    categoria: "Imprenditorialità",
    emoji: "🎯",
    definizione: "Strumento visivo che descrive il modello di business in 9 blocchi: clienti, proposta di valore, canali, relazioni, ricavi, risorse, attività, partner e costi.",
    esempio: "Un aspirante imprenditore compila il Canvas della sua app di car pooling scolastico: identifica i genitori come clienti, la riduzione del traffico come valore e le scuole come partner.",
    area_correlata: "SIS",
  },
  "design thinking": {
    categoria: "Innovazione",
    emoji: "💡",
    definizione: "Processo creativo per risolvere problemi complessi partendo dai bisogni reali delle persone. Fasi: empatia, definizione, ideazione, prototipazione, test.",
    esempio: "Un team usa il design thinking per riprogettare la sala d'aspetto di un ospedale: intervista pazienti, scopre che l'ansia è il vero problema, propone pareti con scene naturali e musica.",
    area_correlata: "SIS",
  },
  "fundraising": {
    categoria: "Imprenditorialità",
    emoji: "💰",
    definizione: "Raccogliere fondi per un progetto: bandi europei, crowdfunding, business angel, venture capital. Richiede saper presentare il progetto in modo convincente.",
    esempio: "Una startup di tecnologia agricola raccoglie 200.000€ da business angel mostrando i dati sui test, il mercato potenziale e il team.",
    area_correlata: "SIS",
  },
  "agilescrum": {
    categoria: "Gestione progetti",
    emoji: "🔁",
    definizione: "Metodo di lavoro iterativo per sviluppare prodotti. Il lavoro è diviso in 'sprint' di 1-4 settimane, con obiettivi chiari, revisioni frequenti e adattamento rapido ai cambiamenti.",
    esempio: "Un team lavora in sprint di 2 settimane: ogni sprint produce una versione funzionante che gli utenti testano. Il feedback orienta il prossimo sprint.",
    area_correlata: "SIS",
  },
  "audit energetico": {
    categoria: "Energia",
    emoji: "🔋",
    definizione: "Analisi sistematica dei consumi energetici di un edificio o un'azienda per identificare dove si spreca energia e cosa si può fare per ridurla.",
    esempio: "Un energy auditor scopre che i motori di una fabbrica tessile consumano energia anche in standby. L'installazione di inverter riduce i consumi del 22%.",
    area_correlata: "ENE",
  },
  "rinnovabili": {
    categoria: "Energia",
    emoji: "☀️",
    definizione: "Tecnologie per produrre energia da fonti che si rigenerano naturalmente: sole, vento, acqua, biomasse, geotermia. Include dimensionamento, installazione e gestione degli impianti.",
    esempio: "Un tecnico dimensiona il fotovoltaico per una scuola: calcola il fabbisogno annuo, l'irraggiamento locale e il numero di pannelli — con payback di 8 anni.",
    area_correlata: "ENE",
  },
  "fotovoltaico": {
    categoria: "Energia solare",
    emoji: "🔆",
    definizione: "Tecnologia che converte la luce solare in energia elettrica. Comprende progettazione, installazione, monitoraggio e manutenzione di impianti solari.",
    esempio: "Un installatore usa PVGIS per stimare la produzione annua di un impianto da 10 kWp su una casa a Milano, scegliendo orientamento e tipo di inverter ottimali.",
    area_correlata: "ENE",
  },
  "eolico": {
    categoria: "Energia eolica",
    emoji: "💨",
    definizione: "Tecnologia che converte l'energia cinetica del vento in elettricità tramite turbine eoliche. Comprende la valutazione del sito, la progettazione e la gestione operativa.",
    esempio: "Un ingegnere eolico analizza i dati del vento di una collina toscana su 20 anni e dimensiona un parco da 5 turbine da 3 MW ciascuna.",
    area_correlata: "ENE",
  },
  "storage energetico": {
    categoria: "Energia",
    emoji: "🔋",
    definizione: "Tecnologie per immagazzinare energia da fonti rinnovabili: batterie litio, accumulatori a flusso, pompaggio idroelettrico, idrogeno verde.",
    esempio: "Un progettista dimensiona 500 kWh di batterie litio per un'isola turistica: coprono la notte e i giorni nuvolosi, riducendo la dipendenza dal generatore diesel dell'80%.",
    area_correlata: "ENE",
  },
  "grid parity": {
    categoria: "Energia",
    emoji: "⚡",
    definizione: "Condizione in cui il costo di produzione da fonti rinnovabili raggiunge o scende sotto il costo dell'energia dalla rete tradizionale. Quando avviene, le rinnovabili diventano convenienti senza incentivi.",
    esempio: "Il fotovoltaico ha raggiunto la grid parity in Italia nel 2020: costo di produzione 0,04 €/kWh vs. prezzo della rete 0,22 €/kWh.",
    area_correlata: "ENE",
  },
  "cad 3d": {
    categoria: "Software di progettazione",
    emoji: "🖥️",
    definizione: "Progettazione assistita da computer in tre dimensioni. Permette di creare modelli digitali di oggetti con forme, dimensioni e materiali precisi, poi inviarli a macchine per la produzione.",
    esempio: "Un progettista meccanico usa il CAD 3D per simulare un componente di motore sotto stress virtuale, verifica che regga i carichi e invia il file alla fresa CNC.",
    area_correlata: "DIS",
  },
  "disegno tecnico": {
    categoria: "Progettazione",
    emoji: "📏",
    definizione: "Linguaggio grafico standardizzato (norme UNI/ISO) per comunicare le caratteristiche di oggetti, edifici o impianti in modo non ambiguo: proiezioni, sezioni, quotatura, tolleranze.",
    esempio: "Un tecnico disegna la sezione di una parete con tutti i materiali isolanti e gli strati impermeabilizzanti. L'impresa la usa per costruire esattamente come progettato.",
    area_correlata: "DIS",
  },
  "tolleranze geometriche": {
    categoria: "Metrologia e qualità",
    emoji: "🔬",
    definizione: "Sistema (GD&T) per specificare quanto un pezzo meccanico può variare dalla forma perfetta pur funzionando. Essenziali per la produzione in serie di pezzi interscambiabili.",
    esempio: "Una tolleranza di planarità di 0,02 mm significa: se la superficie è curva di più, il pezzo non si accoppia con quello adiacente e viene scartato.",
    area_correlata: "DIS",
  },
  "mobilità urbana": {
    categoria: "Trasporti",
    emoji: "🚌",
    definizione: "Studio e gestione di come le persone si spostano in città. Analisi dei flussi di traffico, progettazione di infrastrutture, sviluppo di politiche per ridurre congestione ed emissioni.",
    esempio: "Un mobility planner analizza 2 anni di dati GPS degli autobus, identifica 5 linee cronicamente in ritardo e propone corsie riservate: i tempi medi calano del 18%.",
    area_correlata: "COM",
  },
  "trasporto intermodale": {
    categoria: "Logistica",
    emoji: "🚢",
    definizione: "Sistema di trasporto che combina più modalità (nave, treno, camion) usando container standardizzati. Riduce costi e emissioni rispetto al solo trasporto su strada.",
    esempio: "Un logista organizza il trasporto di 20 tonnellate da Shenzhen a Bologna: nave fino a Genova (21 giorni), treno merci fino a Bologna (3 ore). Risparmio del 30% sull'aereo.",
    area_correlata: "COM",
  },
  "social media": {
    categoria: "Comunicazione digitale",
    emoji: "📲",
    definizione: "Conoscenza delle piattaforme social (Instagram, TikTok, LinkedIn, YouTube) e delle strategie per comunicare efficacemente su ciascuna: formati, algoritmi, metriche di engagement.",
    esempio: "Un social media manager gestisce i profili di un museo: reel su TikTok, stories su Instagram, articoli su LinkedIn — ogni piattaforma con linguaggio e formati diversi.",
    area_correlata: "COM",
  },
  "content strategy": {
    categoria: "Comunicazione digitale",
    emoji: "✍️",
    definizione: "Pianificazione di lungo periodo dei contenuti digitali: cosa comunicare, a chi, su quali canali, con quale frequenza e tono. Collega la comunicazione agli obiettivi di business.",
    esempio: "Una content strategist pianifica il calendario editoriale di un'università: 3 articoli/settimana per gli studenti, 1 webinar/mese per i professionisti, 5 post/giorno su LinkedIn per i recruiter.",
    area_correlata: "COM",
  },
  "seo": {
    categoria: "Marketing digitale",
    emoji: "🔎",
    definizione: "SEO (Search Engine Optimization) migliora la visibilità di un sito nei risultati di ricerca organici su Google. Include ottimizzazione dei testi, struttura del sito, link in entrata.",
    esempio: "Un esperto SEO ottimizza i titoli e le descrizioni di un e-commerce di scarpe artigianali: in 3 mesi il traffico organico aumenta del 65%.",
    area_correlata: "COM",
  },
  "storytelling digitale": {
    categoria: "Comunicazione",
    emoji: "📖",
    definizione: "Arte di raccontare storie attraverso media digitali (video, podcast, social, blog) per creare connessione emotiva con il pubblico.",
    esempio: "Un content creator racconta la storia di un agricoltore biologico in 6 episodi su YouTube: 200.000 visualizzazioni e vendite dirette aumentate del 40%.",
    area_correlata: "COM",
  },
  "analisi ciclo di vita": {
    categoria: "Sostenibilità",
    emoji: "🔄",
    definizione: "Metodologia scientifica (ISO 14040) per valutare l'impatto ambientale di un prodotto in tutte le fasi: estrazione, produzione, trasporto, uso e smaltimento.",
    esempio: "Un'analisi LCA confronta due borse: quella di cotone biologico deve essere usata 149 volte per avere un impatto inferiore alla borsa di plastica — perché il cotone consuma moltissima acqua.",
    area_correlata: "MAT",
  },
  "analisi lca": {
    categoria: "Sostenibilità",
    emoji: "♻️",
    definizione: "LCA (Life Cycle Assessment) è la metodologia ISO per quantificare l'impatto ambientale di un prodotto dalla culla alla tomba: in kg di CO₂ equivalente, litri d'acqua, m² di suolo.",
    esempio: "Un ingegnere usa l'LCA per confrontare imballaggio tetrapack vs. bottiglia di vetro per un succo: analizzando produzione, trasporto e smaltimento per i 20 anni di vita del prodotto.",
    area_correlata: "MAT",
  },
  "materiali compositi": {
    categoria: "Scienza dei materiali",
    emoji: "🔧",
    definizione: "Materiali formati da due o più componenti con proprietà diverse per un risultato superiore a ciascuno da solo. Esempi: fibra di carbonio, cemento armato, fiberglass.",
    esempio: "Una pala di turbina eolica in fibra di carbonio è più leggera e resistente dell'acciaio: pale più lunghe catturano più vento, aumentando la produzione energetica del 15%.",
    area_correlata: "MAT",
  },
  "chimica green": {
    categoria: "Chimica sostenibile",
    emoji: "🧪",
    definizione: "Approccio alla chimica industriale che minimizza l'uso di sostanze pericolose, usa materie prime rinnovabili e progetta processi più efficienti.",
    esempio: "Un chimico sviluppa un solvente derivato da scarti di mais per sostituire i solventi petrolchimici tossici usati nelle vernici: biodegradabile e meno pericoloso per i lavoratori.",
    area_correlata: "MAT",
  },
  "termodinamica applicata": {
    categoria: "Fisica e ingegneria",
    emoji: "🔥",
    definizione: "Applicazione pratica delle leggi della termodinamica a macchine termiche, impianti di riscaldamento/raffreddamento, motori.",
    esempio: "Un ingegnere ottimizza un impianto di cogenerazione: recupera il calore di scarto del motore per riscaldare un edificio, portando l'efficienza totale dal 40% all'80%.",
    area_correlata: "ENE",
  },
  "elettrotecnica": {
    categoria: "Ingegneria",
    emoji: "⚡",
    definizione: "Branca dell'ingegneria che studia produzione, trasmissione e utilizzo dell'energia elettrica: circuiti, macchine elettriche, impianti e sicurezza.",
    esempio: "Un elettrotecnico progetta l'impianto di una nuova fabbrica: calcola le sezioni dei cavi, sceglie i quadri di distribuzione e garantisce il rispetto delle norme CEI.",
    area_correlata: "ENE",
  },
  "simulazione cae": {
    categoria: "Ingegneria",
    emoji: "💻",
    definizione: "CAE (Computer-Aided Engineering) usa software per simulare il comportamento di un oggetto o sistema prima di costruirlo: analisi strutturale, fluidodinamica, termica.",
    esempio: "Un ingegnere simula virtualmente lo schianto frontale di un'auto: vede come si deforma la carrozzeria e se l'abitacolo rimane integro — senza costruire un prototipo fisico.",
    area_correlata: "ENE",
  },
  "gestione batterie bms": {
    categoria: "Energia",
    emoji: "🔋",
    definizione: "BMS (Battery Management System) monitora e protegge le batterie agli ioni di litio: controlla temperatura, tensione e corrente per massimizzare durata e sicurezza.",
    esempio: "Un ingegnere BMS sviluppa il sistema per un'auto elettrica: monitora 400 celle, previene il surriscaldamento e garantisce che la batteria duri 10 anni.",
    area_correlata: "ENE",
  },
  "elettrochimica delle batterie": {
    categoria: "Chimica e energia",
    emoji: "⚗️",
    definizione: "Studio dei processi chimici che avvengono nelle batterie durante carica e scarica: reazioni redox, movimenti ionici, degradazione degli elettrodi.",
    esempio: "Un ricercatore studia perché le batterie litio perdono capacità dopo 500 cicli: trova la causa (dendriti sull'anodo) e sviluppa un nuovo materiale che dura 2000 cicli.",
    area_correlata: "ENE",
  },
  "gestione dei sistemi energetici": {
    categoria: "Energia",
    emoji: "🏭",
    definizione: "Pianificare, controllare e ottimizzare l'uso dell'energia in un edificio, un'azienda o una rete elettrica.",
    esempio: "Un energy manager sposta i carichi energetici nelle ore a tariffa ridotta, usa la batteria per ridurre i picchi di domanda e ottimizza i setpoint di riscaldamento automaticamente.",
    area_correlata: "ENE",
  },
  "simulazione energetica": {
    categoria: "Energia",
    emoji: "📊",
    definizione: "Uso di software per simulare i consumi energetici di un edificio o sistema prima di costruirlo, per confrontare diverse soluzioni e scegliere la più efficiente.",
    esempio: "Un progettista usa EnergyPlus per simulare 3 varianti di isolamento e 4 orientamenti del tetto FV: sceglie la combinazione che minimizza il costo energetico su 20 anni.",
    area_correlata: "ENE",
  },
  "analisi economica lca": {
    categoria: "Sostenibilità",
    emoji: "💹",
    definizione: "Valutazione economica integrata nell'analisi del ciclo di vita: non solo impatto ambientale, ma anche costi e benefici economici di ogni fase.",
    esempio: "Un analista calcola il costo totale di un impianto solare in 25 anni: installazione, manutenzione, sostituzione inverter, smaltimento pannelli — vs. costo energia dalla rete. Risparmio netto: 45.000€.",
    area_correlata: "ENE",
  },
  "programmazione embedded": {
    categoria: "Informatica e IoT",
    emoji: "🤖",
    definizione: "Scrittura di codice per microcontrollori e sistemi integrati con risorse limitate (CPU lenta, poca memoria). Usata in tutti i dispositivi IoT: Arduino, ESP32, STM32.",
    esempio: "Un programmatore scrive il firmware per un sensore di qualità dell'aria: ogni 60 secondi misura CO₂, temperatura e umidità, e invia i dati via WiFi con 0,1W di consumo.",
    area_correlata: "DIG",
  },
  "protocolli di comunicazione iot (mqtt, lora)": {
    categoria: "IoT",
    emoji: "📡",
    definizione: "MQTT e LoRa sono protocolli per dispositivi IoT con bassa potenza. MQTT per connessioni WiFi/4G, LoRa per lunghe distanze senza infrastruttura (raggio 5 km, batteria 5 anni).",
    esempio: "200 sensori di umidità su 50 ettari di vigneto comunicano via LoRa al sistema di irrigazione automatica — senza cavi e senza sostituire le batterie per 5 anni.",
    area_correlata: "DIG",
  },
  "analisi dati in tempo reale": {
    categoria: "Data science",
    emoji: "📈",
    definizione: "Elaborare e interpretare grandi quantità di dati nel momento in cui vengono generati. Usata per allarmi, monitoraggio industriale, trading finanziario, veicoli autonomi.",
    esempio: "Un sistema analizza i dati di 5.000 turbine eoliche in tempo reale: rileva vibrazioni anomale in 3 turbine e attiva la manutenzione preventiva — evitando guasti da 100.000€.",
    area_correlata: "DIG",
  },
  "progettazione sistemi distribuiti": {
    categoria: "Informatica",
    emoji: "🌐",
    definizione: "Progettare sistemi informatici composti da molti componenti che comunicano in rete come se fossero uno solo: affidabili, scalabili e resistenti ai guasti parziali.",
    esempio: "10.000 richieste/secondo vengono distribuite su 50 server in 3 datacenter: se un datacenter va offline, gli altri due gestiscono tutto senza interruzioni.",
    area_correlata: "DIG",
  },
  "wcag 2.1 / 2.2": {
    categoria: "Accessibilità digitale",
    emoji: "♿",
    definizione: "WCAG (Web Content Accessibility Guidelines) definiscono come rendere i contenuti web accessibili a persone con disabilità. Dal 2025 sono obbligatorie per i siti della PA italiana.",
    esempio: "Un'esperta analizza il sito di un comune: trova immagini senza testo alternativo (non accessibili ai ciechi) e contrasti insufficienti. Produce un piano di correzione.",
    area_correlata: "DIG",
  },
  "testing con screen reader": {
    categoria: "Accessibilità digitale",
    emoji: "🎧",
    definizione: "Verificare l'accessibilità di un sito usando software che leggono ad alta voce il contenuto dello schermo (NVDA, JAWS, VoiceOver) — come li usano le persone non vedenti.",
    esempio: "Un tester scopre che il modulo di accesso di una banca non ha etichette leggibili dallo screen reader: un cliente non vedente non può accedere al conto autonomamente.",
    area_correlata: "DIG",
  },
  "universal design": {
    categoria: "Design inclusivo",
    emoji: "🌐",
    definizione: "Approccio progettuale che crea prodotti, ambienti e servizi usabili da tutte le persone senza bisogno di adattamenti speciali. 'Progettare per tutti' come standard, non come eccezione.",
    esempio: "Il MoMA di New York: rampe integrate nell'architettura, bagni accessibili ovunque, audio guide in linguaggio semplice — utili per tutti, essenziali per molti.",
    area_correlata: "DIG",
  },
  "conformità normativa europea (eaa 2025)": {
    categoria: "Normativa",
    emoji: "📜",
    definizione: "L'European Accessibility Act (giugno 2025) obbliga prodotti e servizi digitali privati ad essere accessibili. Un esperto di conformità aiuta le aziende a rispettarla ed evitare sanzioni.",
    esempio: "Un consulente EAA verifica l'app di un supermercato online: controlla testi alternativi, navigazione da tastiera, contrasti — e accompagna il team tecnico nelle correzioni entro scadenza.",
    area_correlata: "DIG",
  },
  "reti tcp/ip avanzate": {
    categoria: "Reti informatiche",
    emoji: "🌐",
    definizione: "Conoscenza approfondita dei protocolli che governano Internet: instradamento dei pacchetti, firewall, load balancer, BGP (il 'GPS' di Internet), diagnosi dei problemi di rete.",
    esempio: "Un network engineer rileva che i video in streaming sono lenti solo dalla Germania: trova il router congestionato a Francoforte e riconfigura il BGP per instradare il traffico via Amsterdam.",
    area_correlata: "COM",
  },
  "geopolitica digitale": {
    categoria: "Geopolitica",
    emoji: "🌍",
    definizione: "Studio di come la tecnologia digitale — Internet, dati, cloud, semiconduttori — influenza le relazioni di potere tra stati e aziende.",
    esempio: "Un analista studia come il blocco USA all'export di chip avanzati alla Cina stia cambiando la catena di produzione globale dei semiconduttori.",
    area_correlata: "COM",
  },
  "sicurezza delle infrastrutture critiche": {
    categoria: "Cybersecurity",
    emoji: "🏭",
    definizione: "Protezione di sistemi essenziali per un paese: reti elettriche, acquedotti, ospedali, trasporti, banche. Un attacco a queste infrastrutture può causare crisi nazionali.",
    esempio: "Un analista simula un attacco alla rete idrica di una città: trova che i sensori di pressione sono controllabili senza autenticazione e propone l'isolamento dei sistemi di controllo.",
    area_correlata: "COM",
  },
  "analisi dei dati di rete": {
    categoria: "Reti e data science",
    emoji: "📊",
    definizione: "Raccogliere, elaborare e interpretare i dati generati dal traffico di rete per rilevare anomalie, ottimizzare le prestazioni e identificare minacce alla sicurezza.",
    esempio: "Un analista rileva che un server interno sta inviando 10GB di dati alle 3:00 verso un IP sconosciuto — segnale di esfiltrazione dati. Blocca il traffico e avvia un'investigazione.",
    area_correlata: "COM",
  },
  "metodologia osint": {
    categoria: "Intelligence e giornalismo",
    emoji: "🔍",
    definizione: "OSINT (Open Source Intelligence) è la raccolta e analisi sistematica di informazioni da fonti pubbliche: web, social media, database, immagini satellitari. Usata da giornalisti investigativi e analisti di sicurezza.",
    esempio: "Un investigatore OSINT verifica l'autenticità di un video virale: usa reverse image search, metadati, ombre per calcolare l'ora, Google Maps per identificare l'edificio — scopre che il video è vecchio di 2 anni.",
    area_correlata: "COM",
  },
  "analisi forense di immagini e video": {
    categoria: "Media forensics",
    emoji: "🎥",
    definizione: "Tecniche per verificare l'autenticità di immagini e video digitali: rilevare manipolazioni, deepfake, metadata falsificati. Strumenti: FotoForensics, InVID, analisi della compressione JPEG.",
    esempio: "Un analista forense verifica una foto 'dell'inondazione di ieri': i metadata EXIF rivelano che è stata scattata 3 anni fa in Brasile. Pubblica la smentita con le prove tecniche.",
    area_correlata: "COM",
  },
  "comprensione degli algoritmi di raccomandazione": {
    categoria: "Intelligenza artificiale",
    emoji: "🤖",
    definizione: "Conoscere come funzionano i sistemi che suggeriscono contenuti su YouTube, Netflix, TikTok, Spotify: usano dati comportamentali per predire cosa vuole l'utente e massimizzare il tempo sulla piattaforma.",
    esempio: "Un ricercatore scopre che YouTube amplifica i video con commenti controversi perché aumentano il tempo di permanenza — portando gradualmente gli utenti verso contenuti sempre più estremi.",
    area_correlata: "COM",
  },
  "giornalismo di dati": {
    categoria: "Giornalismo",
    emoji: "📰",
    definizione: "Approccio giornalistico che usa analisi statistica e visualizzazione di grandi dataset per produrre notizie basate su evidenze quantitative. Combina programmazione, statistica e narrazione.",
    esempio: "Un data journalist analizza 500.000 dichiarazioni dei redditi pubbliche dei parlamentari, le incrocia con gli appalti pubblici vinti dalle loro aziende collegate — e produce un'inchiesta documentata.",
    area_correlata: "COM",
  },
  "linux administration": {
    categoria: "Sistemi operativi",
    emoji: "🐧",
    definizione: "Gestione di server e sistemi Linux: installazione e configurazione del SO, gestione degli utenti e dei permessi, monitoraggio, sicurezza, scripting per l'automazione.",
    esempio: "Un sysadmin Linux automatizza i backup notturni con uno script bash, monitora CPU e memoria con Grafana, e applica le patch di sicurezza senza interrompere i servizi.",
    area_correlata: "DIG",
  },
  "gestione processi e memoria": {
    categoria: "Sistemi operativi",
    emoji: "⚙️",
    definizione: "Come un sistema operativo gestisce i programmi in esecuzione e la memoria RAM: priorità, multitasking, memoria virtuale, prevenzione dei deadlock e dei memory leak.",
    esempio: "Un DevOps engineer scopre un memory leak: un'applicazione web non libera la RAM allocata. Identifica il processo, corregge il codice e risolve i crash che avvenivano ogni 6 ore.",
    area_correlata: "DIG",
  },
  "containerizzazione (docker)": {
    categoria: "DevOps",
    emoji: "🐳",
    definizione: "Docker impacchetta un'applicazione con tutto il suo ambiente in un container portatile. Il container funziona identicamente su qualsiasi macchina, eliminando il problema 'sul mio computer funziona'.",
    esempio: "Un DevOps containerizza un'app web: crea un Dockerfile che installa le dipendenze e configura tutto. Il container viene deployato su 20 server in produzione in 5 minuti.",
    area_correlata: "DIG",
  },
  "automazione infrastrutturale": {
    categoria: "DevOps",
    emoji: "🔄",
    definizione: "Automatizzare la creazione, configurazione e gestione dell'infrastruttura IT usando codice (Infrastructure as Code). Strumenti: Terraform, Ansible. Elimina le operazioni manuali ripetitive.",
    esempio: "Un ingegnere scrive uno script Terraform che in 10 minuti crea automaticamente su AWS: 10 server, 3 database, un load balancer e 5 regole di firewall — invece delle 3 ore manuali.",
    area_correlata: "DIG",
  },
  "crittografia applicata": {
    categoria: "Cybersecurity",
    emoji: "🔐",
    definizione: "Uso pratico degli algoritmi crittografici per proteggere dati e comunicazioni: AES, RSA, SHA-256, firme digitali, certificati TLS. La base di Internet sicuro.",
    esempio: "Un ingegnere implementa la crittografia end-to-end in un'app di messaggistica: ogni messaggio è cifrato con una chiave che solo mittente e destinatario conoscono.",
    area_correlata: "DIG",
  },
  "analisi delle vulnerabilità": {
    categoria: "Cybersecurity",
    emoji: "🔍",
    definizione: "Processo sistematico per identificare i punti deboli di un sistema attraverso scan automatici e test manuali. Produce un rapporto con le vulnerabilità, la loro gravità e le contromisure.",
    esempio: "Un analista trova una vulnerabilità SQL injection su un sito e-commerce che permetterebbe di estrarre tutti i dati dei clienti. La segnala con priorità critica per la correzione immediata.",
    area_correlata: "DIG",
  },
  "risposta agli incidenti": {
    categoria: "Cybersecurity",
    emoji: "🚨",
    definizione: "Processo strutturato per gestire un attacco informatico: rilevamento, contenimento, eradicazione, ripristino e analisi post-incidente. Riduce i danni e previene le recidive.",
    esempio: "Un team di incident response isola i computer colpiti da ransomware, identifica il vettore di ingresso (email di phishing), ripristina dai backup e aggiorna le policy di sicurezza.",
    area_correlata: "DIG",
  },
  "pensiero spaziale": {
    categoria: "Capacità cognitive",
    emoji: "🎯",
    definizione: "Abilità di visualizzare e manipolare mentalmente oggetti e forme nello spazio tridimensionale. Essenziale per designer, architetti e ingegneri. Si sviluppa con disegno tecnico e modellazione.",
    esempio: "Un designer con ottimo pensiero spaziale immagina come sarà un oggetto da 5 angolazioni diverse senza disegnarlo — poi lo traduce in un modello 3D preciso in poche ore.",
    area_correlata: "DIS",
  },
  "comunicazione visiva": {
    categoria: "Design",
    emoji: "🎨",
    definizione: "Trasmettere informazioni e idee attraverso elementi visivi — grafica, immagini, infografiche, layout — in modo chiaro, efficace ed esteticamente equilibrato.",
    esempio: "Un designer trasforma un rapporto annuale di 80 pagine in un documento di 20 con grafici e visualizzazioni: stessa informazione, comprensibile in 5 minuti.",
    area_correlata: "DIS",
  },
  "software 3d": {
    categoria: "Software",
    emoji: "🖥️",
    definizione: "Padronanza di software di modellazione, rendering o animazione 3D: Blender, Maya, Tinkercad, Fusion 360. Usati in architettura, design industriale, cinema, videogiochi, stampa 3D.",
    esempio: "Un visual designer usa Blender per creare la visualizzazione fotorealistica di un nuovo edificio: luce solare in diverse ore del giorno, materiali delle facciate, persone in scala.",
    area_correlata: "DIS",
  },
  "chimica dei polimeri": {
    categoria: "Chimica",
    emoji: "🧬",
    definizione: "Studio della struttura, sintesi e proprietà delle macromolecole (polimeri) come plastiche, gomme, fibre sintetiche e biomateriali. Permette di progettare nuovi materiali con proprietà su misura.",
    esempio: "Un chimico studia perché il PLA (bioplastica) si degrada solo a 58°C e non nella compostiera di casa. Modifica la struttura molecolare per accelerare la degradazione anche a 30°C.",
    area_correlata: "MAT",
  },
  "progettazione per il disassemblaggio": {
    categoria: "Design sostenibile",
    emoji: "🔩",
    definizione: "Approccio progettuale che considera fin dall'inizio come il prodotto verrà smontato a fine vita per recuperare i materiali. Usa giunzioni meccaniche invece di colle e materiali compatibili.",
    esempio: "Un designer applica questo approccio a uno smartphone: viti standard, batteria removibile, schermo staccabile con riscaldamento. Si smonta in 10 minuti invece di 4 ore.",
    area_correlata: "MAT",
  },
  "analisi del ciclo di vita (lca)": {
    categoria: "Sostenibilità",
    emoji: "♻️",
    definizione: "Metodologia ISO per quantificare l'impatto ambientale di un prodotto dalla culla alla tomba: estrazione, produzione, trasporto, uso, fine vita. Risultato in kg di CO₂ equivalente.",
    esempio: "Una maglietta di cotone biologico usa meno pesticidi ma 7.000 litri d'acqua. Quella di poliestere riciclato usa meno acqua ma rilascia microplastiche. Il risultato dipende da quale impatto si considera prioritario.",
    area_correlata: "MAT",
  },
};

/** Cerca una competenza nel glossario (case-insensitive, ignora spazi extra) */
export function cercaCompetenza(chiave: string): CompetenzaEntry | null {
  const normalized = chiave.toLowerCase().trim();
  return GLOSSARIO[normalized] ?? null;
}

/** Tutte le categorie presenti nel glossario */
export const CATEGORIE = [...new Set(Object.values(GLOSSARIO).map((c) => c.categoria))].sort();
